# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.srcs/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/design_1_BUTTON_axi_smc_0.xci
# IP: The module: 'design_1_BUTTON_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/bd_c675.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_0/bd_c675_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_1/bd_c675_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_2/bd_c675_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_3/bd_c675_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_4/bd_c675_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_5/bd_c675_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_6/bd_c675_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_7/bd_c675_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_8/bd_c675_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_9/bd_c675_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_10/bd_c675_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_11/bd_c675_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_12/bd_c675_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_13/bd_c675_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_14/bd_c675_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_15/bd_c675_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_16/bd_c675_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_17/bd_c675_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_18/bd_c675_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_19/bd_c675_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_20/bd_c675_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_21/bd_c675_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_22/bd_c675_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_23/bd_c675_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_24/bd_c675_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_25/bd_c675_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_26/bd_c675_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_27/bd_c675_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_28/bd_c675_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_29/bd_c675_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_30/bd_c675_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_31/bd_c675_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_32/bd_c675_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_33/bd_c675_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_34/bd_c675_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_35/bd_c675_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_36/bd_c675_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_37/bd_c675_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_38/bd_c675_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_39/bd_c675_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_1/bd_c675_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_1/bd_c675_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_2/bd_c675_arinsw_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_3/bd_c675_rinsw_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_4/bd_c675_awinsw_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_5/bd_c675_winsw_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_6/bd_c675_binsw_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_7/bd_c675_aroutsw_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_8/bd_c675_routsw_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_9/bd_c675_awoutsw_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_10/bd_c675_woutsw_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_11/bd_c675_boutsw_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_12/bd_c675_arni_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_13/bd_c675_rni_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_14/bd_c675_awni_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_15/bd_c675_wni_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_16/bd_c675_bni_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_20/bd_c675_s00a2s_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_21/bd_c675_sarn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_22/bd_c675_srn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_23/bd_c675_sawn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_24/bd_c675_swn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_25/bd_c675_sbn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_26/bd_c675_m00s2a_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_27/bd_c675_m00arn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_28/bd_c675_m00rn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_29/bd_c675_m00awn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_30/bd_c675_m00wn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_31/bd_c675_m00bn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_33/bd_c675_m01s2a_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_34/bd_c675_m01arn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_35/bd_c675_m01rn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_36/bd_c675_m01awn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_37/bd_c675_m01wn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_38/bd_c675_m01bn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_BUTTON_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_BUTTON_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.srcs/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/design_1_BUTTON_axi_smc_0.xci
# IP: The module: 'design_1_BUTTON_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/bd_c675.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_0/bd_c675_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_1/bd_c675_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_2/bd_c675_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_3/bd_c675_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_4/bd_c675_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_5/bd_c675_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_6/bd_c675_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_7/bd_c675_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_8/bd_c675_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_9/bd_c675_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_10/bd_c675_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_11/bd_c675_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_12/bd_c675_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_13/bd_c675_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_14/bd_c675_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_15/bd_c675_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_16/bd_c675_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_17/bd_c675_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_18/bd_c675_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_19/bd_c675_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_20/bd_c675_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_21/bd_c675_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_22/bd_c675_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_23/bd_c675_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_24/bd_c675_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_25/bd_c675_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_26/bd_c675_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_27/bd_c675_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_28/bd_c675_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_29/bd_c675_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_30/bd_c675_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_31/bd_c675_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_32/bd_c675_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_33/bd_c675_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_34/bd_c675_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_35/bd_c675_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_36/bd_c675_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_37/bd_c675_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_38/bd_c675_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_39/bd_c675_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_1/bd_c675_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_1/bd_c675_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_2/bd_c675_arinsw_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_3/bd_c675_rinsw_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_4/bd_c675_awinsw_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_5/bd_c675_winsw_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_6/bd_c675_binsw_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_7/bd_c675_aroutsw_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_8/bd_c675_routsw_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_9/bd_c675_awoutsw_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_10/bd_c675_woutsw_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_11/bd_c675_boutsw_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_12/bd_c675_arni_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_13/bd_c675_rni_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_14/bd_c675_awni_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_15/bd_c675_wni_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_16/bd_c675_bni_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_20/bd_c675_s00a2s_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_21/bd_c675_sarn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_22/bd_c675_srn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_23/bd_c675_sawn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_24/bd_c675_swn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_25/bd_c675_sbn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_26/bd_c675_m00s2a_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_27/bd_c675_m00arn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_28/bd_c675_m00rn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_29/bd_c675_m00awn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_30/bd_c675_m00wn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_31/bd_c675_m00bn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_33/bd_c675_m01s2a_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_34/bd_c675_m01arn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_35/bd_c675_m01rn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_36/bd_c675_m01awn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_37/bd_c675_m01wn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/bd_0/ip/ip_38/bd_c675_m01bn_0_ooc.xdc

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_BUTTON_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_BUTTON_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
