# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1_BUTTON/design_1_BUTTON.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_BUTTON || ORIG_REF_NAME==design_1_BUTTON} -quiet] -quiet

# IP: bd/design_1_BUTTON/ip/design_1_BUTTON_proc_sys_reset_0_0/design_1_BUTTON_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_BUTTON_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_BUTTON_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1_BUTTON/ip/design_1_BUTTON_clk_wiz_0/design_1_BUTTON_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_BUTTON_clk_wiz_0 || ORIG_REF_NAME==design_1_BUTTON_clk_wiz_0} -quiet] -quiet

# IP: bd/design_1_BUTTON/ip/design_1_BUTTON_microblaze_riscv_0_0/design_1_BUTTON_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_BUTTON_microblaze_riscv_0_0 || ORIG_REF_NAME==design_1_BUTTON_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/design_1_BUTTON/ip/design_1_BUTTON_dlmb_v10_0/design_1_BUTTON_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_BUTTON_dlmb_v10_0 || ORIG_REF_NAME==design_1_BUTTON_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_1_BUTTON/ip/design_1_BUTTON_ilmb_v10_0/design_1_BUTTON_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_BUTTON_ilmb_v10_0 || ORIG_REF_NAME==design_1_BUTTON_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_1_BUTTON/ip/design_1_BUTTON_dlmb_bram_if_cntlr_0/design_1_BUTTON_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_BUTTON_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_BUTTON_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_1_BUTTON/ip/design_1_BUTTON_ilmb_bram_if_cntlr_0/design_1_BUTTON_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_BUTTON_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_BUTTON_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_1_BUTTON/ip/design_1_BUTTON_lmb_bram_0/design_1_BUTTON_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_BUTTON_lmb_bram_0 || ORIG_REF_NAME==design_1_BUTTON_lmb_bram_0} -quiet] -quiet

# IP: bd/design_1_BUTTON/ip/design_1_BUTTON_mdm_1_0/design_1_BUTTON_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_BUTTON_mdm_1_0 || ORIG_REF_NAME==design_1_BUTTON_mdm_1_0} -quiet] -quiet

# IP: bd/design_1_BUTTON/ip/design_1_BUTTON_axi_uartlite_0_0/design_1_BUTTON_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_BUTTON_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_BUTTON_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_1_BUTTON/ip/design_1_BUTTON_axi_smc_0/design_1_BUTTON_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_BUTTON_axi_smc_0 || ORIG_REF_NAME==design_1_BUTTON_axi_smc_0} -quiet] -quiet

# IP: bd/design_1_BUTTON/ip/design_1_BUTTON_axi_gpio_0_0/design_1_BUTTON_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_BUTTON_axi_gpio_0_0 || ORIG_REF_NAME==design_1_BUTTON_axi_gpio_0_0} -quiet] -quiet

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_BUTTON/project_1_BUTTON.gen/sources_1/bd/design_1_BUTTON/design_1_BUTTON_ooc.xdc
