# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1_FND/design_1_FND.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FND || ORIG_REF_NAME==design_1_FND} -quiet] -quiet

# IP: bd/design_1_FND/ip/design_1_FND_proc_sys_reset_0_0/design_1_FND_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FND_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_FND_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1_FND/ip/design_1_FND_clk_wiz_0/design_1_FND_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FND_clk_wiz_0 || ORIG_REF_NAME==design_1_FND_clk_wiz_0} -quiet] -quiet

# IP: bd/design_1_FND/ip/design_1_FND_microblaze_riscv_0_0/design_1_FND_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FND_microblaze_riscv_0_0 || ORIG_REF_NAME==design_1_FND_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/design_1_FND/ip/design_1_FND_dlmb_v10_0/design_1_FND_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FND_dlmb_v10_0 || ORIG_REF_NAME==design_1_FND_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_1_FND/ip/design_1_FND_ilmb_v10_0/design_1_FND_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FND_ilmb_v10_0 || ORIG_REF_NAME==design_1_FND_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_1_FND/ip/design_1_FND_dlmb_bram_if_cntlr_0/design_1_FND_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FND_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_FND_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_1_FND/ip/design_1_FND_ilmb_bram_if_cntlr_0/design_1_FND_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FND_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_FND_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_1_FND/ip/design_1_FND_lmb_bram_0/design_1_FND_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FND_lmb_bram_0 || ORIG_REF_NAME==design_1_FND_lmb_bram_0} -quiet] -quiet

# IP: bd/design_1_FND/ip/design_1_FND_mdm_1_0/design_1_FND_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FND_mdm_1_0 || ORIG_REF_NAME==design_1_FND_mdm_1_0} -quiet] -quiet

# IP: bd/design_1_FND/ip/design_1_FND_axi_uartlite_0_0/design_1_FND_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FND_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_FND_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_1_FND/ip/design_1_FND_axi_smc_0/design_1_FND_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FND_axi_smc_0 || ORIG_REF_NAME==design_1_FND_axi_smc_0} -quiet] -quiet

# IP: bd/design_1_FND/ip/design_1_FND_axi_gpio_0_0/design_1_FND_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FND_axi_gpio_0_0 || ORIG_REF_NAME==design_1_FND_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1_FND/ip/design_1_FND_axi_gpio_0_1/design_1_FND_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FND_axi_gpio_0_1 || ORIG_REF_NAME==design_1_FND_axi_gpio_0_1} -quiet] -quiet

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_FND/project_1_FND.gen/sources_1/bd/design_1_FND/design_1_FND_ooc.xdc
