# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1_hello/design_1_hello.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_hello || ORIG_REF_NAME==design_1_hello} -quiet] -quiet

# IP: bd/design_1_hello/ip/design_1_hello_proc_sys_reset_0_0/design_1_hello_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_hello_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_hello_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1_hello/ip/design_1_hello_clk_wiz_0/design_1_hello_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_hello_clk_wiz_0 || ORIG_REF_NAME==design_1_hello_clk_wiz_0} -quiet] -quiet

# IP: bd/design_1_hello/ip/design_1_hello_microblaze_riscv_0_0/design_1_hello_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_hello_microblaze_riscv_0_0 || ORIG_REF_NAME==design_1_hello_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/design_1_hello/ip/design_1_hello_dlmb_v10_0/design_1_hello_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_hello_dlmb_v10_0 || ORIG_REF_NAME==design_1_hello_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_1_hello/ip/design_1_hello_ilmb_v10_0/design_1_hello_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_hello_ilmb_v10_0 || ORIG_REF_NAME==design_1_hello_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_1_hello/ip/design_1_hello_dlmb_bram_if_cntlr_0/design_1_hello_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_hello_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_hello_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_1_hello/ip/design_1_hello_ilmb_bram_if_cntlr_0/design_1_hello_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_hello_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_hello_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_1_hello/ip/design_1_hello_lmb_bram_0/design_1_hello_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_hello_lmb_bram_0 || ORIG_REF_NAME==design_1_hello_lmb_bram_0} -quiet] -quiet

# IP: bd/design_1_hello/ip/design_1_hello_mdm_1_0/design_1_hello_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_hello_mdm_1_0 || ORIG_REF_NAME==design_1_hello_mdm_1_0} -quiet] -quiet

# IP: bd/design_1_hello/ip/design_1_hello_axi_uartlite_0_0/design_1_hello_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_hello_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_hello_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_1_hello/ip/design_1_hello_axi_smc_0/design_1_hello_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_hello_axi_smc_0 || ORIG_REF_NAME==design_1_hello_axi_smc_0} -quiet] -quiet

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_hello/project_1_hello.gen/sources_1/bd/design_1_hello/design_1_hello_ooc.xdc
