# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1_LED/design_1_LED.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_LED || ORIG_REF_NAME==design_1_LED} -quiet] -quiet

# IP: bd/design_1_LED/ip/design_1_LED_microblaze_riscv_0_0/design_1_LED_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_LED_microblaze_riscv_0_0 || ORIG_REF_NAME==design_1_LED_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/design_1_LED/ip/design_1_LED_dlmb_v10_0/design_1_LED_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_LED_dlmb_v10_0 || ORIG_REF_NAME==design_1_LED_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_1_LED/ip/design_1_LED_ilmb_v10_0/design_1_LED_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_LED_ilmb_v10_0 || ORIG_REF_NAME==design_1_LED_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_1_LED/ip/design_1_LED_dlmb_bram_if_cntlr_0/design_1_LED_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_LED_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_LED_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_1_LED/ip/design_1_LED_ilmb_bram_if_cntlr_0/design_1_LED_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_LED_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_LED_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_1_LED/ip/design_1_LED_lmb_bram_0/design_1_LED_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_LED_lmb_bram_0 || ORIG_REF_NAME==design_1_LED_lmb_bram_0} -quiet] -quiet

# IP: bd/design_1_LED/ip/design_1_LED_mdm_1_0/design_1_LED_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_LED_mdm_1_0 || ORIG_REF_NAME==design_1_LED_mdm_1_0} -quiet] -quiet

# IP: bd/design_1_LED/ip/design_1_LED_clk_wiz_1_0/design_1_LED_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_LED_clk_wiz_1_0 || ORIG_REF_NAME==design_1_LED_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_1_LED/ip/design_1_LED_rst_clk_wiz_1_100M_0/design_1_LED_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_LED_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_1_LED_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/design_1_LED/ip/design_1_LED_axi_gpio_0_0/design_1_LED_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_LED_axi_gpio_0_0 || ORIG_REF_NAME==design_1_LED_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1_LED/ip/design_1_LED_axi_smc_0/design_1_LED_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_LED_axi_smc_0 || ORIG_REF_NAME==design_1_LED_axi_smc_0} -quiet] -quiet

# IP: bd/design_1_LED/ip/design_1_LED_proc_sys_reset_0_0/design_1_LED_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_LED_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_LED_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1_LED/ip/design_1_LED_axi_uartlite_0_0/design_1_LED_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_LED_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_LED_axi_uartlite_0_0} -quiet] -quiet

# XDC: /home/appletea/workspace_onedevice_2/SoC/project_1_LED/project_1_LED.gen/sources_1/bd/design_1_LED/design_1_LED_ooc.xdc
